name: Check for ticket availability

on:
  schedule:
    - cron: '*/30 * * * *'  # toutes les 30 minutes
  workflow_dispatch:        # permet aussi de le lancer manuellement

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install

      - name: Run script
        run: python main.py
