name: Check for ticket availability

on:
  schedule:
    - cron: '*/30 * * * *'  # toutes les 30 minutes
  workflow_dispatch:        # exécutable manuellement

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install
          python -m playwright install chromium

      - name: Run script
        run: python main.py

      - name: Upload screenshot
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: widget-screenshot
          path: screenshot.png
